### ISSUE TITLE
Merge MemMapVerticle in to InferenceVerticle

### ISSUE THREAD

**Issue by agibsonccc** [KonduitAI/konduit-serving#70]
@ShamsUlAzeem @maxpumperla  @wmeddie  https://github.com/KonduitAI/konduit-serving/blob/4f5e01525160719e49057a4b4425a03b6688f325/konduit-serving-core/src/main/java/ai/konduit/serving/verticles/nd4j/memmap/MemMapVerticle.java#L69

What do we want MemMapVerticle doing? Do we want to merge this in to InferenceVerticle as a configuration instead?

Do we want more than one verticle? Collapsing them seems like it will make things easier.
I know for example, we could also just make mem map a pipeline step instead.

**Comment by wmeddie** [comment]
I think the advantages of MemoryMaps instead of embedding them into models would be:

1. Sharing a single map between many models
2. Hosting a map that's too big to fit in GPU memory on a separate server/process with enough host RAM.

So in that sense, it's always a pipeline step from the view of the model, but to do 2 you'll need to be able to possibly specify a remote server address to send the transform request to.  In that case we do need it to be possible to deploy a map on a standalone server.

**Comment by ShamsUlAzeem** [comment]
@agibsonccc I can see it being part of a pipeline. We can have a large array stored in the server and do inferences based on indices. We won't have to send large arrays through http requests.

**Comment by maxpumperla** [comment]
absolutely in favor of having this as config for InferenceVerticle. we might have more than one verticle (e.g. retraining), but those two should go together I think.

**Comment by agibsonccc** [comment]
Hey folks - I'll work on merging this in this week.
