### ISSUE TITLE
Consider making it compulsory to name input names of steps 

### ISSUE THREAD

**Issue by philip-khor** [KonduitAI/konduit-serving#90]
https://github.com/KonduitAI/konduit-serving/blob/d5866436d3bcd25ea043860b9654ce9cef17e98c/python/tests/test_python_serving.py#L13-L27

In the above Python test, the dictionary passed to predict has to have the `"default"` key, however it's not clear to the user why. User's first impulse is to use `first` as key. 

User code may be clearer if `input_name` is a non-optional argument to `.step()`, e.g. 

```python
python_step = PythonStep().step(
    input_name="input",
    python_config=python_config
)
```

**Comment by maxpumperla** [comment]
@philip-khor thanks for the idea. it's good that we think about this. we were initially coming from the "other" direction, in which literally everything was named "default" (which we're now hiding). I think we should find a middle ground here.

@ShamsUlAzeem what do you think?

**Comment by ShamsUlAzeem** [comment]
Yeah it's a good discussion. I think it's related to #42. And I think it already handles the edge case where if there's no input key given it automatically assumes that the key for that input is `default`: https://github.com/KonduitAI/konduit-serving/blob/5ea250f769d4e5d20ebaa09603764749581105f3/python/konduit/client.py#L39. So, by that logic you can just send the input as `np.load('../data/input-0.npy')` instead of `data_input = {'default': np.load('../data/input-0.npy')}` 

After #42 is solved, this would make much more sense and the user would be able to give columnar names as input column keys when sending data to the server through python client.

**Comment by ShamsUlAzeem** [comment]
We now do this automatically: https://github.com/KonduitAI/konduit-serving/pull/98
